### ISSUE TITLE
4.2.2 EML schema link broken

### ISSUE THREAD

**Issue by laijasmine** [NCEAS/datateam-training#121]
Looks like the [link](https://knb.ecoinformatics.org/external//emlparser/docs/eml-2.1.1/index.html) in chapter 4.2.2 refers to an older version of EML (2.1.1). But i'm not sure what the original was supposed to show from here: https://eml.ecoinformatics.org/eml-schema.html

**Comment by jeanetteclark** [comment]
Yeah, the updated schema links are a bit problematic. The new schema docs don't supply as many direct links as the old ones did, so we should think about how to point to the correct place in the docs (maybe more screenshots?)

Also just as a sidenote, although we referencing EML 2.2.0 in these docs, we currently still primarily work in EML 2.1.1 since the web interface doesn't support editing EML 2.2.0 docs yet (though it will soon)
