### ISSUE TITLE
Sections after PI Correspondence don't show up in the reference 

### ISSUE THREAD

**Issue by laijasmine** [NCEAS/datateam-training#276]

**Comment by BrennieDev** [comment]
@laijasmine I had a little time today while I was getting my RStudio environments up to speed to look into this.

The issue is in `pi_correspondence/replicate_dataset.Rmd` - For some reason, the function to set eval = FALSE for the other chunks in the Rmd does not play nicely with the bookdown rendering.

```
knitr::opts_chunk$set(eval = F)
```

If we take this out and just put a `eval = FALSE` on each chunk that needs it instead, things start to work as expected. I can submit a PR for this if you'd like, otherwise I'll leave you that info to do with as you see fit!

**Comment by laijasmine** [comment]
ah that makes sense! Thanks for catching it @BrennieDev . Feel free to put in a PR for it and remove the knitr line
